services:
  minio:
    build:
      context: ./docker/MinIO
    image: minio/minio:latest
    container_name: minio-test
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    command: server --address ":9000" --console-address ":9001" /data
    volumes:
      - minio-data:/data
    restart: always

volumes:
  minio-data:
    driver: local
